# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
debug: false # Enable debug logs.
trace: false # Enable trace logs.

server:
  port: 9011

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.29.8:3306/select_lession_database?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ENC(YiYjVwTulDGN//YaB3KbuA==)
    password: ENC(SfQaj8C0NpWCN2UbhNZ4wBQbfzi6YTtZ)
    type: com.alibaba.druid.pool.DruidDataSource

  application:
    name: service-ribbon

  banner:
    charset: UTF-8
    location: classpath:banner.txt

logging:
  level:
    org:
      springframework:
        web: INFO
    Hibernate: INFO
  config: classpath:logback.xml

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://47.96.29.8:9010/eureka/

jasypt:
  encryptor:
    password: 19941017
    property:
      prefix: "ENC("
      suffix: ")"

mybatis:
  mapper-locations: classpath:mapper/*.xml
