CREATE DATABASE IF NOT EXISTS select_lession_database;

USE select_lession_database;

CREATE TABLE IF NOT EXISTS T_USER_STUDENTS
(
  STUDENT_ID VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '学号',
  USER_NAME VARBINARY(32) NOT NULL COMMENT '姓名',
  USER_PASSWORD VARCHAR(64) NOT NULL COMMENT '密码',
  USER_PHONE VARCHAR(11) COMMENT '电话',
  SCHOOL_CLASS VARCHAR(32) NOT NULL COMMENT '班级',
  USER_SEX BOOL COMMENT '性别',
  USER_AGE INTEGER COMMENT '年龄',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间'
);ALTER TABLE T_USER_STUDENTS COMMENT = '用户库';

CREATE TABLE IF NOT EXISTS T_SYS_CLASSES(
  CLASS_NAME VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '班级名称',
  CLASS_LEVEL INTEGER NOT NULL COMMENT '年级',
  CLASS_MEMBER INTEGER NOT NULL COMMENT '人数',
  DEPARTMENT VARCHAR(32) DEFAULT '校' NOT NULL COMMENT '系',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间'
);ALTER TABLE T_SYS_CLASSES COMMENT = '班级库';

CREATE TABLE IF NOT EXISTS T_USER_TEACHERS
(
  TEACHER_ID VARCHAR(32) NOT NULL COMMENT '教师ID',
  TEACHER_NAME VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '姓名',
  USER_PASSWORD VARCHAR(64) NOT NULL COMMENT '密码',
  USER_PHONE VARCHAR(11) NOT NULL COMMENT '电话',
  RESEARCH_AREA VARCHAR(32) NOT NULL COMMENT '研究方向',
  USER_SEX BOOL COMMENT '性别',
  USER_AGE INTEGER COMMENT '年龄',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间'
);ALTER TABLE T_USER_TEACHERS COMMENT = '教师库';

CREATE TABLE IF NOT EXISTS T_SYS_COURSES(
  COURSE_NAME VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '课程名称',
  ROOM_LOCATION VARCHAR(32) NOT NULL,
  MAX_MEMBER INTEGER NOT NULL COMMENT '最大人数',
  LECTURER VARCHAR(32) NOT NULL COMMENT '主讲教师',
  COURSE_TIME VARCHAR(32) NOT NULL COMMENT '上课时间',
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间'
);ALTER TABLE T_SYS_COURSES COMMENT = '课程库';

CREATE TABLE IF NOT EXISTS T_ATTR_COURSES(
  STUDENT_ID VARCHAR(32) PRIMARY KEY NOT NULL COMMENT '学号',
  COURSE_NAME_1 VARCHAR(32),
  COURSE_NAME_2 VARCHAR(32),
  COURSE_NAME_3 VARCHAR(32)
);ALTER TABLE T_ATTR_COURSES COMMENT = '学生选课库';